name: Manual Deploy to Vercel Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd=dist

      - name: Deploy to Vercel from dist folder
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd=dist
